### ISSUE TITLE
Setup Git Submodule of `test-repo` to reduce git noise

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gitea#29]
At present, both the [**`test-repo`**](https://github.com/dwyl/gitea/tree/ec1338a27e8e5042ffd6b0a874e2307e7d53d349/test-repo) and [**`tmp/test-repo`**](https://github.com/dwyl/gitea/tree/ec1338a27e8e5042ffd6b0a874e2307e7d53d349/tmp/test-repo) are included in the `gitea` repo on GitHub: 

![gitea-repo-test-included](https://user-images.githubusercontent.com/194400/170279324-391f4ba6-6fec-4f39-a828-ef521cd0ba25.png)

By contrast the https://github.com/dwyl/gogs repo does not have these folders/files, instead it has a git submodule:
![gogs-test-submodule](https://user-images.githubusercontent.com/194400/170280449-e9d9dd0b-1e67-43f5-9a9f-2880cb3849b4.png)

This leads to commits being added to the root `.git` history when tests are run:
![image](https://user-images.githubusercontent.com/194400/170276605-50f70814-6392-4004-aded-c3b96b2b956b.png)

> **Note**: not picking on Simon's PR, mine had the same issue. 
this is just the most _recent_ instance which highlights that it's still a problem. 
![image](https://user-images.githubusercontent.com/194400/170280592-0258c77f-07bd-451f-995b-3b8f69f20800.png)

# Todo

+ [x] `delete` the undesired directories from the project.
+ [x] `create` a sub-module: https://git-scm.com/book/en/v2/Git-Tools-Submodules
+ [x] Confirm that it worked.
+ [x] Open PR
+ [x] Fix this!! 🙏

**Comment by nelsonic** [comment]
PR: #36 assigned to @SimonLab for review. 🙏

**Comment by nelsonic** [comment]
PR #36 merged. Order restored! 

![gitea-submodule](https://user-images.githubusercontent.com/194400/170731205-72103785-2d55-4a56-aacc-4bef1a2ff08e.png)

Closing. ✅
